# modified for mothur-test
# 6/18/2013

# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = ../gtest-1.6.0

# Where to find mothur code.
MOTHUR_INC_DIR = ..
MOTHUR_DIR = ../mothur

# Where to find user code.
USER_DIR = .

# Flags passed to the preprocessor.
CPPFLAGS += -I$(GTEST_DIR)/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra

CXXFLAGS += -DUSE_READLINE
LIBS = \
    -lreadline\
    -lncurses

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = hello_test svm_test

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS)

clean :
	rm -f $(TESTS) gtest.a gtest_main.a *.o

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

hello.o : $(USER_DIR)/hello.cpp $(USER_DIR)/hello.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/hello.cpp

hello_test.o : $(USER_DIR)/hello_test.cpp \
                     $(USER_DIR)/hello.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/hello_test.cpp

# moved -lpthread to end of line since I use an Ubuntu-derived Linux
# see issue 391 on googletest website
hello_test : hello.o hello_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@ -lpthread

###############
# build a test for the mothur classifysharedcommand
# this is not working - there are many dependencies
#classifysharedcommand_test.o : $(USER_DIR)/classifysharedcommand_test.cpp \
#                $(MOTHUR_DIR)/classifysharedcommand.h $(GTEST_HEADERS)
#	$(CXX) $(CPPFLAGS) -I$(MOTHUR_DIR) $(CXXFLAGS) -c $(USER_DIR)/classifysharedcommand_test.cpp
#
#classifysharedcommand_test : $(MOTHUR_DIR)/classifysharedcommand.o $(MOTHUR_DIR)/mothurout.o $(MOTHUR_DIR)/abstractdecisiontree.o $(MOTHUR_DIR)/inputdata.o classifysharedcommand_test.o gtest_main.a
#	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@ -lpthread $(LIBS)
################

# build a test for classes in the mothur svm.cpp file
svm_test.o : $(USER_DIR)/svm_test.cpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) -I$(MOTHUR_INC_DIR) $(CXXFLAGS) -c $(USER_DIR)/svm_test.cpp

svm_test : $(MOTHUR_DIR)/mothurout.o $(MOTHUR_DIR)/inputdata.o \
        $(MOTHUR_DIR)/calculator.o $(MOTHUR_DIR)/groupmap.o $(MOTHUR_DIR)/counttable.o \
        $(MOTHUR_DIR)/listvector.o $(MOTHUR_DIR)/sharedlistvector.o $(MOTHUR_DIR)/ordervector.o $(MOTHUR_DIR)/sharedordervector.o \
        $(MOTHUR_DIR)/rabundvector.o $(MOTHUR_DIR)/sharedrabundvector.o $(MOTHUR_DIR)/sharedrabundfloatvector.o $(MOTHUR_DIR)/sabundvector.o $(MOTHUR_DIR)/sharedsabundvector.o \
        $(MOTHUR_DIR)/sharedutilities.o \
        $(MOTHUR_DIR)/svm.o svm_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@ -lpthread